# Generated by Django 6.0.5 on 2026-05-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biometric_user_id',
            field=models.CharField(blank=True, help_text='ID number used by the biometric attendance device', max_length=50, null=True),
        ),
    ]
