# Generated by Django 6.0.5 on 2026-05-11 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_computed_status_and_more'),
        ('employees', '0002_employee_biometric_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='attendance.workschedule'),
        ),
    ]
