# Generated by Django 6.0.5 on 2026-05-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pagibig_contribution_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed monthly Pag-IBIG contribution to deduct from payroll.', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='philhealth_contribution_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed monthly PhilHealth contribution to deduct from payroll.', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='sss_contribution_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed monthly SSS contribution to deduct from payroll.', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed monthly withholding tax to deduct from payroll.', max_digits=10),
        ),
    ]
