# Generated by Django 6.0.5 on 2026-06-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_add_contribution_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pay_basis',
            field=models.CharField(choices=[('daily', 'Daily / Payable-days'), ('monthly', 'Monthly (fixed salary includes holidays)')], default='daily', help_text='Daily: paid per payable day. Monthly: fixed salary already includes paid holidays (no-work holidays are not docked).', max_length=10),
        ),
    ]
