# Generated by Django 6.0.5 on 2026-06-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_pay_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowed_clock_in_from',
            field=models.TimeField(blank=True, help_text='Earliest allowed clock-in for flexible employees.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='allowed_clock_in_until',
            field=models.TimeField(blank=True, help_text='Latest allowed clock-in for flexible employees.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_break_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Break minutes assumed for flexible computation when not recorded.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='flexible_schedule_enabled',
            field=models.BooleanField(default=False, help_text='If on, attendance uses required daily hours instead of a fixed start/end.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_policy',
            field=models.CharField(choices=[('not_allowed', 'Not Allowed'), ('automatic', 'Automatic'), ('request_required', 'Request Required'), ('management_review', 'Management Review')], default='not_allowed', help_text="Controls how this employee's overtime is paid by payroll.", max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='required_daily_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Hours a flexible employee must complete per day.', max_digits=4),
        ),
    ]
