# Generated by Django 6.0.5 on 2026-06-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_allowed_clock_in_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily pay rate for daily-paid employees. Monthly employees use basic salary; daily employees use daily rate. Leave blank to compute from basic salary (÷ 26).', max_digits=10, null=True),
        ),
    ]
