# Generated by Django 6.0.5 on 2026-06-04 09:40

import datetime
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_daily_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allow_other_registered_locations',
            field=models.BooleanField(default=False, help_text='Allows future flexible/mobile rules to include other registered locations without bypassing validation.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='attendance_policy_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('flexible', 'Flexible')], default='fixed', help_text='Fixed employees follow assigned schedules; flexible employees use configured required hours in a later attendance phase.', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='flexible_day_offs',
            field=models.JSONField(blank=True, default=list, help_text='Weekday codes configured as flexible day-offs.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='night_differential_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='night_differential_end_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AddField(
            model_name='employee',
            name='night_differential_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Additional night differential percentage configured for payroll in a later phase.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='employee',
            name='night_differential_start_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='default_break_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Break minutes assumed for flexible computation when not recorded.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='required_daily_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Hours a flexible employee must complete per day.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
