# Generated by Django 6.0.5 on 2026-06-04 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_allow_other_registered_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='flexible_overtime_grace_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Overtime starts only after this many minutes beyond required daily hours.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
