# Generated by Django 6.0.5 on 2026-06-04 12:15

from django.db import migrations, models


def normalize_overtime_policy(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Employee.objects.filter(overtime_policy='not_allowed').update(overtime_policy='no_ot')
    Employee.objects.filter(overtime_policy='management_review').update(
        overtime_policy='request_required'
    )


def restore_legacy_overtime_policy(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Employee.objects.filter(overtime_policy='no_ot').update(overtime_policy='not_allowed')


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_flexible_overtime_grace_minutes'),
    ]

    operations = [
        migrations.RunPython(normalize_overtime_policy, restore_legacy_overtime_policy),
        migrations.AlterField(
            model_name='employee',
            name='overtime_policy',
            field=models.CharField(choices=[('no_ot', 'No OT'), ('request_required', 'Request Required'), ('automatic', 'Automatic')], default='no_ot', help_text='No OT = never pay overtime. Request Required = employee requests, HR approves, and attendance caps payable OT. Automatic = pay actual computed overtime automatically.', max_length=20),
        ),
    ]
