# Generated by Django 6.0.5 on 2026-06-16 00:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_overtime_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ordinary-day overtime rate for this employee (1.25 = 125%). Leave blank to use the company default overtime multiplier.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
    ]
