# Generated by Django 6.0.5 on 2026-06-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_overtime_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime_counting_rule',
            field=models.CharField(blank=True, choices=[('', 'Inherit from company default'), ('exact', 'Exact minutes (no rounding)'), ('30', '30-minute blocks'), ('60', '1-hour blocks'), ('120', '2-hour blocks')], default='', help_text="How this employee's detected overtime is counted for pay. Leave blank to inherit the company default. Block rules floor DOWN to the last completed block (e.g. 59 min of OT counts as 30 under the 30-minute rule).", max_length=10, verbose_name='Overtime counting rule'),
        ),
    ]
