# Generated by Django 6.0.5 on 2026-07-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_chat_support_display_name_and_more'),
        ('employees', '0012_employee_overtime_counting_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowed_chat_companies',
            field=models.ManyToManyField(blank=True, help_text='Other companies this employee may chat with (cross-company).', related_name='chat_enabled_employees', to='companies.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_use_chat',
            field=models.BooleanField(default=False, help_text='Allow this employee to use portal chat when company chat is enabled.'),
        ),
    ]
