# Generated by Django 6.0.5 on 2026-08-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_daily_allowance_deduct_undertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowance_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', help_text='Daily is attendance-based. Monthly is prorated by payroll period calendar dates.', max_length=10, verbose_name='Allowance type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='daily_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Allowance amount per selected allowance type.', max_digits=10, verbose_name='Allowance amount'),
        ),
    ]
