# Generated by Django 6.0.5 on 2026-06-02 07:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_attendance_auto_delete_portal_logs_and_more'),
        ('employees', '0005_employee_pay_basis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHolidayPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_no_work_pay_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('regular_worked_multiplier', models.DecimalField(decimal_places=2, default=2, max_digits=4)),
                ('special_nonworking_default_paid', models.BooleanField(default=False)),
                ('special_nonworking_no_work_pay_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('special_nonworking_worked_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.30'), max_digits=4)),
                ('special_working_worked_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('company_local_default_paid', models.BooleanField(default=True)),
                ('company_local_worked_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_policy', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Company holiday policies',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('regular', 'Regular Holiday'), ('special_non_working', 'Special (Non-Working)'), ('special_working', 'Special (Working)'), ('company', 'Company Holiday'), ('local', 'Local Holiday')], max_length=30)),
                ('source', models.CharField(choices=[('system_default', 'System Default'), ('company', 'Company')], default='company', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('no_work_pay_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('worked_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='companies.company')),
            ],
            options={
                'ordering': ['date', 'name'],
                'unique_together': {('company', 'date', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HolidayException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_observed', models.BooleanField(default=False)),
                ('is_paid_override', models.BooleanField(blank=True, null=True)),
                ('no_work_pay_pct_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('worked_multiplier_override', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_exceptions', to='employees.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_exceptions', to='employees.employee')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='holidays.holiday')),
            ],
            options={
                'ordering': ['holiday', 'department', 'employee'],
            },
        ),
    ]
