# Generated by Django 6.0.5 on 2026-06-02 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_attendance_auto_delete_portal_logs_and_more'),
        ('employees', '0006_employee_allowed_clock_in_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('requested_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('approved_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Hours actually approved. Blank until reviewed; falls back to requested hours on approval.', max_digits=5, null=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto Approved')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('employee', 'Employee'), ('detected', 'Detected'), ('hr', 'HR')], default='employee', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_overtime_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['company', 'status'], name='overtime_ov_company_4985a1_idx'), models.Index(fields=['employee', 'date'], name='overtime_ov_employe_0dc033_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
