# Generated by Django 6.0.5 on 2026-06-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overtimerequest',
            unique_together=set(),
        ),
    ]
