from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse
from unittest.mock import patch

from accounts.models import UserCompanyAccess

from .models import Company


class CompanyPayslipSettingsViewTests(TestCase):
    def setUp(self):
        self.company_a = Company.objects.create(name="Company A", email="a@test.com")
        self.company_b = Company.objects.create(name="Company B", email="b@test.com")

        self.user_a = User.objects.create_user(username="company_user_a", password="testpass123")
        self.user_b = User.objects.create_user(username="company_user_b", password="testpass123")

        UserCompanyAccess.objects.create(
            user=self.user_a, company=self.company_a, role="company_admin", is_active=True
        )
        UserCompanyAccess.objects.create(
            user=self.user_b, company=self.company_b, role="company_admin", is_active=True
        )

    def test_payslip_settings_requires_login(self):
        response = self.client.get(reverse("companies:payslip_settings", args=[self.company_a.pk]))
        self.assertEqual(response.status_code, 302)
        self.assertIn(reverse("accounts:login"), response.url)

    def test_user_can_open_own_company_payslip_settings(self):
        self.client.login(username="company_user_a", password="testpass123")
        response = self.client.get(reverse("companies:payslip_settings", args=[self.company_a.pk]))
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, "companies/payslip_settings.html")
        self.assertContains(response, "Payslip Settings")

    def test_user_cannot_open_other_company_payslip_settings(self):
        self.client.login(username="company_user_a", password="testpass123")
        response = self.client.get(reverse("companies:payslip_settings", args=[self.company_b.pk]))
        self.assertEqual(response.status_code, 403)

    @patch("licenses.middleware.is_license_active", return_value=True)
    @patch("licenses.clock_guard.check_clock_rollback", return_value=False)
    def test_user_can_update_payslip_settings(self, _mock_rollback, _mock_license_active):
        self.client.login(username="company_user_a", password="testpass123")
        response = self.client.post(
            reverse("companies:payslip_settings", args=[self.company_a.pk]),
            {
                "payslip_company_display_name": "Company A Payroll",
                "payslip_company_address": "Test Address",
                "payslip_template_style": "classic_excel",
                "payslip_accent_color": "#0D1B2A",
                "payslip_show_company_logo": "on",
                "payslip_show_rates": "on",
                "payslip_show_attendance_summary": "on",
                "payslip_show_overtime_breakdown": "on",
                "payslip_show_received_by": "on",
                "payslip_footer_note": "Generated by HR",
                "attendance_selfie_retention_days": "45",
            },
            follow=True,
        )
        self.assertEqual(response.status_code, 200)

        self.company_a.refresh_from_db()
        self.assertEqual(self.company_a.payslip_company_display_name, "Company A Payroll")
        self.assertEqual(self.company_a.payslip_accent_color, "#0D1B2A")
        self.assertEqual(self.company_a.attendance_selfie_retention_days, 45)

    def test_company_selfie_retention_default_is_30_days(self):
        self.assertEqual(self.company_a.attendance_selfie_retention_days, 30)
