# Generated by Django 6.0.5 on 2026-05-10 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('hr_admin', 'HR Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=30)),
                ('is_active_stafforyx', models.BooleanField(default=True)),
                ('can_access_dashboard', models.BooleanField(default=True)),
                ('can_manage_employees', models.BooleanField(default=False)),
                ('can_manage_attendance', models.BooleanField(default=False)),
                ('can_manage_leaves', models.BooleanField(default=False)),
                ('can_manage_payroll', models.BooleanField(default=False)),
                ('can_manage_documents', models.BooleanField(default=False)),
                ('can_manage_announcements', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_export_data', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('can_manage_license', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='companies.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='employees.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stafforyx_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
