# Generated by Django 6.0.5 on 2026-06-03 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_company_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sidebar_accent',
            field=models.CharField(blank=True, default='', help_text='Active menu-item color (hex). Blank derives from the sidebar color.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{6})$', 'Enter a valid 6-digit hex color, e.g. #0D1B2A.')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sidebar_color',
            field=models.CharField(blank=True, default='', help_text='Sidebar background color (hex). Blank uses the default theme.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{6})$', 'Enter a valid 6-digit hex color, e.g. #0D1B2A.')]),
        ),
    ]
