# Generated by Django 6.0.5 on 2026-07-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_sidebar_accent_userprofile_sidebar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_chat',
            field=models.BooleanField(default=False, help_text='Access admin chat inbox, message employees, create official groups, and audit.'),
        ),
    ]
