# Generated by Django 6.0.5 on 2026-07-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group_avatar',
            field=models.ImageField(blank=True, help_text='Optional logo for official group conversations.', null=True, upload_to='messaging/group_avatars/'),
        ),
    ]
