# Generated by Django 6.0.5 on 2026-07-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'Image'), ('gif', 'GIF'), ('voice', 'Voice')], max_length=10),
        ),
    ]
