# Generated by Django 6.0.5 on 2026-06-04 15:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_advance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashadvancerequest',
            name='deduction_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashadvancerequest',
            name='deduction_status',
            field=models.CharField(choices=[('released', 'Released'), ('scheduled_for_deduction', 'Scheduled for Deduction'), ('partially_deducted', 'Partially Deducted'), ('deducted', 'Deducted / Paid Off')], default='released', help_text='How far this released cash advance has been deducted via payroll.', max_length=30),
        ),
        migrations.AddField(
            model_name='cashadvancerequest',
            name='fully_deducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashadvancerequest',
            name='total_deducted_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of payroll deduction lines applied to this cash advance.', max_digits=12),
        ),
    ]
