# Generated by Django 6.0.5 on 2026-05-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payslip_accent_color',
            field=models.CharField(default='#1565C0', help_text='Hex color for payslip accent elements (e.g. #1565C0).', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_company_address',
            field=models.TextField(blank=True, help_text='Override address shown on payslips. Leave blank to use company address.'),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_company_display_name',
            field=models.CharField(blank=True, help_text='Override company name shown on payslips. Leave blank to use company name.', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_footer_note',
            field=models.TextField(blank=True, help_text='Optional note printed at the bottom of every payslip.'),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_show_attendance_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_show_company_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_show_overtime_breakdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_show_rates',
            field=models.BooleanField(default=True, help_text='Show daily rate, hourly rate, and overtime rates section.'),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_show_received_by',
            field=models.BooleanField(default=True, help_text='Show "Received by" signature line.'),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_template_style',
            field=models.CharField(choices=[('classic_excel', 'Classic Excel'), ('modern', 'Modern')], default='classic_excel', max_length=30),
        ),
    ]
