# Generated by Django 6.0.5 on 2026-05-28 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_payslip_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='attendance_selfie_retention_days',
            field=models.PositiveIntegerField(default=30, help_text='Attendance selfie photos older than this number of days can be deleted by the cleanup command. Attendance logs remain, but image files are removed.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
