# Generated by Django 6.0.5 on 2026-05-28 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_attendance_selfie_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='attendance_auto_delete_portal_logs',
            field=models.BooleanField(default=True, help_text='Allow automatic cleanup command to delete old attendance portal logs.'),
        ),
        migrations.AddField(
            model_name='company',
            name='attendance_log_blocked_attempts',
            field=models.BooleanField(default=True, help_text='Log blocked clock attempts (network, schedule, selfie/GPS requirement failures).'),
        ),
        migrations.AddField(
            model_name='company',
            name='attendance_log_clock_actions',
            field=models.BooleanField(default=True, help_text='Log time in/time out attempts and outcomes.'),
        ),
        migrations.AddField(
            model_name='company',
            name='attendance_log_page_opened_events',
            field=models.BooleanField(default=False, help_text='Log each portal page visit/open event.'),
        ),
        migrations.AddField(
            model_name='company',
            name='attendance_portal_log_retention_days',
            field=models.PositiveIntegerField(default=30, help_text='Delete attendance portal logs older than this number of days during log cleanup.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
