# Generated by Django 6.0.5 on 2026-06-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_attendance_auto_delete_portal_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payslip_prepared_by_name',
            field=models.CharField(blank=True, help_text='Name auto-filled into the "Prepared By" area of every payslip.', max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_prepared_by_signature',
            field=models.ImageField(blank=True, help_text='Uploaded or drawn signature shown above the Prepared By line.', null=True, upload_to='companies/signatures/'),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_prepared_by_title',
            field=models.CharField(blank=True, default='HR/Payroll Officer', help_text='Title shown under the preparer name (e.g. HR/Payroll Officer).', max_length=100),
        ),
    ]
