# Generated by Django 6.0.5 on 2026-06-08 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_attendance_ip_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='attendance_qr_token_lifetime_seconds',
            field=models.PositiveIntegerField(default=60, help_text='How long each rotating attendance QR token remains valid. Allowed range: 30-300 seconds.', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='company',
            name='attendance_qr_validation_enabled',
            field=models.BooleanField(default=False, help_text='Require employees to scan a live branch QR code before clocking in/out. This validates physical presence at an approved attendance location.', verbose_name='Require rotating QR code for attendance'),
        ),
    ]
