# Generated by Django 6.0.5 on 2026-06-08 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_attendance_qr_token_lifetime_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='attendance_auto_delete_qr_scan_logs',
            field=models.BooleanField(default=False, help_text='Allows cleanup command to remove old QR scan audit log records. QR scan logs are audit records, so keep this disabled if your policy requires review.', verbose_name='Auto delete old QR scan logs'),
        ),
        migrations.AddField(
            model_name='company',
            name='attendance_auto_delete_qr_tokens',
            field=models.BooleanField(default=True, help_text='Allows cleanup command to remove expired QR token records.', verbose_name='Auto delete expired QR tokens'),
        ),
        migrations.AddField(
            model_name='company',
            name='attendance_qr_scan_log_retention_days',
            field=models.PositiveIntegerField(default=90, help_text='How long QR scan audit logs are kept.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='QR scan log retention days'),
        ),
        migrations.AddField(
            model_name='company',
            name='attendance_qr_token_retention_days',
            field=models.PositiveIntegerField(default=1, help_text='Expired QR tokens older than this can be deleted safely. This does not delete attendance records.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='QR token retention days'),
        ),
        migrations.AlterField(
            model_name='company',
            name='attendance_qr_token_lifetime_seconds',
            field=models.PositiveIntegerField(default=60, help_text='How long each rotating QR code remains valid before it refreshes.', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)], verbose_name='QR token lifetime seconds'),
        ),
    ]
