# Generated by Django 6.0.5 on 2026-06-16 00:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_attendance_auto_delete_qr_scan_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_overtime_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='Ordinary-day overtime rate applied to employees without their own override (1.25 = 125%). Holiday and night-differential rates are configured separately.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Default overtime multiplier'),
        ),
    ]
