# Generated by Django 6.0.5 on 2026-06-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_default_overtime_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_overtime_counting_rule',
            field=models.CharField(choices=[('exact', 'Exact minutes (no rounding)'), ('30', '30-minute blocks'), ('60', '1-hour blocks'), ('120', '2-hour blocks')], default='exact', help_text='How detected overtime is counted for pay. Exact = pay every minute. Block rules floor DOWN to the last completed block (e.g. under the 30-minute rule, 59 min of OT counts as 30 min). Useful for flexible employees who accumulate many small overtime minutes.', max_length=10, verbose_name='Default overtime counting rule'),
        ),
    ]
