# Generated by Django 6.0.5 on 2026-07-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_default_overtime_counting_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='chat_support_display_name',
            field=models.CharField(blank=True, default='', help_text='Persona name shown to employees in admin support chats. Blank uses global default.', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_chat_enabled',
            field=models.BooleanField(default=False, help_text='Master switch: allow employee portal chat for this company.'),
        ),
    ]
