# Generated by Django 6.0.5 on 2026-05-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='cutoff_type',
            field=models.CharField(blank=True, choices=[('custom', 'Custom'), ('semi_monthly', 'Semi-Monthly'), ('monthly', 'Monthly'), ('weekly', 'Weekly')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
