# Generated by Django 6.0.5 on 2026-06-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payroll_v2_breakdown_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='holiday_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='holiday_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='holiday_worked_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
