# Generated by Django 6.0.5 on 2026-06-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollrecord_holiday_days_payrollrecord_holiday_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='night_differential_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='night_differential_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='night_differential_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
