# Generated by Django 6.0.5 on 2026-06-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_advance', '0002_cashadvancerequest_deduction_started_at_and_more'),
        ('payroll', '0005_payrollrecord_night_differential_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolladjustment',
            name='source_cash_advance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deduction_adjustments', to='cash_advance.cashadvancerequest'),
        ),
    ]
