# Generated by Django 6.0.5 on 2026-06-16 00:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrolladjustment_source_cash_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='overtime_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.25'), max_digits=4),
        ),
    ]
