# Generated by Django 6.0.5 on 2026-06-16 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_default_overtime_multiplier'),
        ('payroll', '0007_payrollrecord_overtime_multiplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('payroll_count', models.PositiveIntegerField(default=0)),
                ('attendance_count', models.PositiveIntegerField(default=0)),
                ('portal_log_count', models.PositiveIntegerField(default=0)),
                ('qr_log_count', models.PositiveIntegerField(default=0)),
                ('overtime_count', models.PositiveIntegerField(default=0)),
                ('leave_count', models.PositiveIntegerField(default=0)),
                ('ca_count', models.PositiveIntegerField(default=0)),
                ('cleared_counts', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('is_cleared', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_archive_batches', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_batches', to='companies.company')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_archive_batches', to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_batches', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['company', 'generated_at'], name='payroll_arc_company_05dbce_idx'), models.Index(fields=['is_cleared'], name='payroll_arc_is_clea_ebfce1_idx')],
            },
        ),
    ]
