# Generated by Django 6.0.5 on 2026-05-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='license',
            name='license_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
