# Generated by Django 6.0.5 on 2026-06-16 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0009_company_default_overtime_multiplier'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('leave_request', 'Leave request'), ('overtime_request', 'Overtime request'), ('cash_advance_request', 'Cash advance request'), ('payroll', 'Payroll'), ('attendance', 'Attendance'), ('document', 'Document'), ('announcement', 'Announcement'), ('system', 'System')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'notification_type'], name='notificatio_recipie_df577d_idx'), models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx'), models.Index(fields=['company', 'notification_type', 'is_read'], name='notificatio_company_847645_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'notification_type', 'content_type', 'object_id'), name='unique_notification_per_recipient_object_type')],
            },
        ),
    ]
