# Generated by Django 6.0.5 on 2026-06-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leave_request', 'Leave request'), ('overtime_request', 'Overtime request'), ('cash_advance_request', 'Cash advance request'), ('incident_report', 'Incident report'), ('payroll', 'Payroll'), ('attendance', 'Attendance'), ('document', 'Document'), ('announcement', 'Announcement'), ('system', 'System')], max_length=40),
        ),
    ]
