# Generated by Django 6.0.5 on 2026-05-11 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='computed_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='overtime_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='total_work_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='undertime_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_minutes', models.PositiveIntegerField(default=15)),
                ('break_minutes', models.PositiveIntegerField(default=60)),
                ('required_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('overtime_after', models.TimeField(blank=True, help_text='Overtime counted after this time. Leave blank to use End Time.', null=True)),
                ('work_monday', models.BooleanField(default=True)),
                ('work_tuesday', models.BooleanField(default=True)),
                ('work_wednesday', models.BooleanField(default=True)),
                ('work_thursday', models.BooleanField(default=True)),
                ('work_friday', models.BooleanField(default=True)),
                ('work_saturday', models.BooleanField(default=False)),
                ('work_sunday', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='companies.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
