# Generated by Django 6.0.5 on 2026-05-26 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_computed_status_and_more'),
        ('companies', '0001_initial'),
        ('employees', '0003_employee_work_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_code', models.CharField(help_text='Short unique code used to identify this device (e.g. HQ-DOOR-01).', max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('device_type', models.CharField(choices=[('zkteco', 'ZKTeco'), ('hikvision', 'Hikvision'), ('dahua', 'Dahua'), ('anviz', 'Anviz'), ('other', 'Other')], default='zkteco', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, help_text='Secret key for authenticating future sync requests from this device.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to='companies.company')),
            ],
            options={
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'device_code')},
            },
        ),
        migrations.CreateModel(
            name='BiometricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_user_id', models.CharField(max_length=50)),
                ('punch_time', models.DateTimeField()),
                ('punch_type', models.CharField(choices=[('unknown', 'Unknown'), ('check_in', 'Check In'), ('check_out', 'Check Out'), ('break_in', 'Break In'), ('break_out', 'Break Out')], default='unknown', max_length=20)),
                ('raw_status_code', models.CharField(blank=True, max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='attendance.attendancerecord')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_logs', to='companies.company')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='attendance.biometricdevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='employees.employee')),
            ],
            options={
                'ordering': ['-punch_time'],
                'indexes': [models.Index(fields=['company', 'punch_time'], name='attendance__company_b83fb3_idx'), models.Index(fields=['company', 'biometric_user_id'], name='attendance__company_1f016b_idx'), models.Index(fields=['processed'], name='attendance__process_b120bc_idx')],
            },
        ),
    ]
