# Generated by Django 6.0.5 on 2026-05-27 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_add_biometric_device_and_log'),
        ('companies', '0001_initial'),
        ('employees', '0003_employee_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('portal', 'WiFi Portal'), ('biometric', 'Biometric')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Office WiFi, Cebu Branch', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Exact public IP address allowed for clock-in/out.', null=True)),
                ('cidr_range', models.CharField(blank=True, help_text='CIDR range, e.g. 112.198.10.0/24. Leave blank if using exact IP.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('require_selfie', models.BooleanField(default=False)),
                ('require_gps', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_locations', to='companies.company')),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='portal_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.attendancelocation'),
        ),
        migrations.CreateModel(
            name='AttendancePortalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('page_open', 'Page Opened'), ('time_in', 'Time In'), ('time_out', 'Time Out'), ('blocked', 'Blocked')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('blocked_reason', models.TextField(blank=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_logs', to='attendance.attendancelocation')),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_logs', to='attendance.attendancerecord')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_logs', to='companies.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_logs', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='attendance__company_e881d5_idx'), models.Index(fields=['employee', 'created_at'], name='attendance__employe_b57cae_idx'), models.Index(fields=['status'], name='attendance__status_bc3cbd_idx')],
            },
        ),
    ]
