# Generated by Django 6.0.5 on 2026-05-27 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_add_attendance_location_portal'),
        ('companies', '0001_initial'),
        ('employees', '0003_employee_work_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('grace_minutes', models.PositiveIntegerField(default=10)),
                ('allow_early_clock_in_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before start_time an employee may clock in via the portal.')),
                ('overtime_after_minutes', models.PositiveIntegerField(default=0, help_text='Minutes after end_time before overtime is counted. 0 = OT starts at end_time.')),
                ('is_overnight', models.BooleanField(default=False, help_text='Check if this shift crosses midnight (e.g. 10 PM – 6 AM).')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='companies.company')),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('custom_start_time', models.TimeField(blank=True, help_text='Override the template start time. Requires custom_end_time.', null=True)),
                ('custom_end_time', models.TimeField(blank=True, help_text='Override the template end time. Requires custom_start_time.', null=True)),
                ('break_minutes', models.PositiveIntegerField(blank=True, help_text='Leave blank to use template value.', null=True)),
                ('grace_minutes', models.PositiveIntegerField(blank=True, help_text='Leave blank to use template value.', null=True)),
                ('is_rest_day', models.BooleanField(default=False, help_text='Employee is not expected to work on this date.')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generated'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_schedules', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_schedules', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='employees.employee')),
                ('shift_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_schedules', to='attendance.shifttemplate')),
            ],
            options={
                'ordering': ['schedule_date', 'employee'],
                'unique_together': {('employee', 'schedule_date')},
            },
        ),
    ]
