# Generated by Django 6.0.5 on 2026-05-28 05:08

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_add_shift_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceportallog',
            name='gps_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='attendanceportallog',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to=attendance.models.portal_selfie_upload_path),
        ),
    ]
