# Generated by Django 6.0.5 on 2026-06-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendanceportallog_gps_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='night_differential_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
