# Generated by Django 6.0.5 on 2026-06-08 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendanceportallog_validation_method'),
        ('companies', '0007_company_attendance_qr_token_lifetime_seconds_and_more'),
        ('employees', '0010_alter_employee_overtime_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceportallog',
            name='validation_method',
            field=models.CharField(blank=True, choices=[('IP', 'IP Match'), ('QR', 'QR Match'), ('QR_GPS', 'QR + GPS'), ('QR_SELFIE', 'QR + Selfie'), ('QR_GPS_SELFIE', 'QR + GPS + Selfie'), ('QR_IP_DISABLED_GPS_SELFIE', 'QR + IP Disabled + GPS/Selfie'), ('GPS_SELFIE', 'GPS + Selfie'), ('IP_DISABLED_GPS_SELFIE', 'IP Disabled — GPS/Selfie'), ('BLOCKED', 'Blocked'), ('BLOCKED_QR_MISSING', 'Blocked - QR Missing'), ('BLOCKED_QR_EXPIRED', 'Blocked - QR Expired'), ('BLOCKED_QR_INVALID', 'Blocked - QR Invalid'), ('BLOCKED_QR_UNAUTHORIZED', 'Blocked - QR Unauthorized'), ('BLOCKED_GPS_MISSING', 'Blocked - GPS Missing'), ('BLOCKED_SELFIE_MISSING', 'Blocked - Selfie Missing')], help_text='Which validation path was used for this portal interaction.', max_length=30),
        ),
        migrations.CreateModel(
            name='AttendanceKioskDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_kiosk_devices', to='attendance.attendancelocation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_kiosk_devices', to='companies.company')),
            ],
            options={
                'ordering': ['company', 'attendance_location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceQRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='attendance.attendancelocation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_qr_tokens', to='companies.company')),
                ('kiosk_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='attendance.attendancekioskdevice')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceQRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(choices=[('validate', 'Validate'), ('time_in', 'Time In'), ('time_out', 'Time Out')], default='validate', max_length=20)),
                ('result', models.CharField(choices=[('success', 'Success'), ('missing', 'Missing'), ('expired', 'Expired'), ('invalid', 'Invalid'), ('inactive_device', 'Inactive Device'), ('inactive_location', 'Inactive Location'), ('unauthorized', 'Unauthorized'), ('rate_limited', 'Rate Limited')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scan_logs', to='attendance.attendancelocation')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_qr_scan_logs', to='companies.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scan_logs', to='employees.employee')),
                ('kiosk_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scan_logs', to='attendance.attendancekioskdevice')),
                ('qr_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='attendance.attendanceqrtoken')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancekioskdevice',
            index=models.Index(fields=['company', 'is_active'], name='attendance__company_30e436_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancekioskdevice',
            index=models.Index(fields=['attendance_location', 'is_active'], name='attendance__attenda_a12666_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceqrtoken',
            index=models.Index(fields=['company', 'expires_at'], name='attendance__company_528af2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceqrtoken',
            index=models.Index(fields=['kiosk_device', 'expires_at'], name='attendance__kiosk_d_b44a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceqrtoken',
            index=models.Index(fields=['attendance_location', 'expires_at'], name='attendance__attenda_20e7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceqrtoken',
            index=models.Index(fields=['is_active', 'expires_at'], name='attendance__is_acti_e2dcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceqrscanlog',
            index=models.Index(fields=['company', 'created_at'], name='attendance__company_bf11ba_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceqrscanlog',
            index=models.Index(fields=['employee', 'created_at'], name='attendance__employe_e34be0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceqrscanlog',
            index=models.Index(fields=['result', 'created_at'], name='attendance__result_d583cc_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceqrscanlog',
            index=models.Index(fields=['token_hash'], name='attendance__token_h_6b9858_idx'),
        ),
    ]
