# Generated by Django 6.0.5 on 2026-06-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendanceportallog_validation_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceqrscanlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attendanceqrscanlog',
            name='result',
            field=models.CharField(choices=[('success', 'Success'), ('missing', 'Missing'), ('expired', 'Expired'), ('invalid', 'Invalid'), ('inactive_device', 'Inactive Device'), ('inactive_location', 'Inactive Location'), ('unauthorized', 'Unauthorized'), ('rate_limited', 'Rate Limited')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='attendanceqrtoken',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendanceqrtoken',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
