# Generated by Django 6.0.5 on 2026-06-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendanceqrscanlog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='actual_overtime_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Raw detected overtime before the counting/rounding rule is applied.'),
        ),
    ]
