# Generated by Django 6.0.5 on 2026-08-19 03:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendancerecord_actual_overtime_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='late_deduction_rate_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount deducted per total late hour. Leave blank to use the employee hourly rate.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='undertime_deduction_rate_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount deducted per total undertime hour. Leave blank to use the employee hourly rate.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='grace_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Late minutes start only after this grace period.'),
        ),
    ]
