# Generated by Django 6.0.5 on 2026-08-19 03:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def preserve_existing_fixed_rates(apps, schema_editor):
    WorkSchedule = apps.get_model('attendance', 'WorkSchedule')
    WorkSchedule.objects.filter(
        late_deduction_rate_per_hour__isnull=False,
    ).update(use_employee_hourly_rate_for_late=False)
    WorkSchedule.objects.filter(
        undertime_deduction_rate_per_hour__isnull=False,
    ).update(use_employee_hourly_rate_for_undertime=False)


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_workschedule_late_deduction_rate_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='use_employee_hourly_rate_for_late',
            field=models.BooleanField(default=True, help_text="When enabled, late deduction uses each employee's computed hourly rate.", verbose_name='Use employee hourly rate for late deduction'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='use_employee_hourly_rate_for_undertime',
            field=models.BooleanField(default=True, help_text="When enabled, undertime deduction uses each employee's computed hourly rate.", verbose_name='Use employee hourly rate for undertime deduction'),
        ),
        migrations.RunPython(preserve_existing_fixed_rates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workschedule',
            name='late_deduction_rate_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount deducted per total late hour when employee hourly rate is off.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='undertime_deduction_rate_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount deducted per total undertime hour when employee hourly rate is off.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
