# Generated by Django 6.0.5 on 2026-08-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_workschedule_use_employee_hourly_rate_for_late_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='half_day_cutoff_time',
            field=models.TimeField(blank=True, help_text='Optional. Clock-outs at or before this time are marked half-day and undertime is capped to this cutoff.', null=True),
        ),
    ]
